name: twitter_clone_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  hooks_riverpod: ^2.4.9
  image_picker: ^1.0.5
  carousel_slider: ^4.2.1
  timeago: ^3.6.0
  any_link_preview: ^3.0.1
  like_button: ^2.0.5
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1  
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  uuid: ^4.2.2
  equatable: ^2.0.5
  pull_to_refresh_flutter3: ^2.0.2
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.7
  dio: ^5.4.0
  photo_view: ^0.14.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/

flutter_native_splash:
  color: "#e1f5fe"
  image: assets/images/twit_logo.png
  color_dark: "#042a49"
  image_dark: assets/images/twit_dark_logo.png
  android_12:
    image: assets/images/twit_logo.png
    color: "#e1f5fe"
  fullscreen: true
